In [135]:
import pandas as pd
import numpy as np

In [2]:
aiRatings = pd.read_csv('../Recommder/A1Ratings.csv')

In [129]:
aiRatings

,User,260: Star Wars: Episode IV - A New Hope (1977),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),1: Toy Story (1995),2028: Saving Private Ryan (1998),296: Pulp Fiction (1994),...,2396: Shakespeare in Love (1998),2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995)
0,755,1.0,5.0,2.0,NaN,4.0,4.0,2.0,2.0,NaN,...,2.0,NaN,5.0,2.0,NaN,4.0,2.0,5.0,NaN,NaN
1,5277,5.0,3.0,NaN,2.0,4.0,2.0,1.0,NaN,NaN,...,3.0,2.0,2.0,NaN,2.0,NaN,5.0,1.0,3.0,NaN
2,1577,NaN,NaN,NaN,5.0,2.0,NaN,4.0,NaN,NaN,...,NaN,1.0,4.0,4.0,1.0,1.0,2.0,3.0,1.0,3.0
3,4388,NaN,3.0,NaN,NaN,NaN,1.0,2.0,3.0,4.0,...,NaN,4.0,1.0,3.0,5.0,NaN,5.0,1.0,1.0,2.0
4,1202,4.0,3.0,4.0,1.0,4.0,1.0,NaN,4.0,NaN,...,5.0,1.0,NaN,4.0,NaN,3.0,5.0,5.0,NaN,NaN
5,3823,2.0,4.0,4.0,4.0,NaN,NaN,3.0,1.0,4.0,...,5.0,2.0,4.0,NaN,1.0,NaN,NaN,3.0,NaN,2.0
6,5448,NaN,NaN,3.0,1.0,1.0,4.0,NaN,5.0,2.0,...,1.0,NaN,NaN,3.0,NaN,1.0,NaN,NaN,5.0,2.0
7,5347,4.0,NaN,NaN,NaN,3.0,2.0,2.0,NaN,3.0,...,NaN,2.0,3.0,2.0,4.0,NaN,1.0,3.0,5.0,NaN
8,4117,5.0,1.0,NaN,4.0,2.0,4.0,4.0,4.0,NaN,...,2.0,3.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,5.0
9,2765,4.0,2.0,NaN,5.0,3.0,NaN,4.0,3.0,4.0,...,NaN,NaN,2.0,NaN,NaN,2.0,5.0,1.0,NaN,NaN
10,5450,2.0,1.0,5.0,NaN,NaN,5.0,5.0,NaN,NaN,...,NaN,3.0,2.0,NaN,NaN,1.0,NaN,2.0,1.0,4.0
11,139,3.0,5.0,2.0,NaN,2.0,NaN,2.0,NaN,1.0,...,3.0,NaN,3.0,NaN,2.0,5.0,NaN,NaN,NaN,2.0
12,1940,2.0,3.0,NaN,5.0,4.0,NaN,4.0,5.0,NaN,...,NaN,2.0,4.0,NaN,3.0,NaN,NaN,NaN,5.0,NaN
13,3118,3.0,NaN,3.0,NaN,2.0,NaN,3.0,NaN,NaN,...,NaN,1.0,2.0,2.0,3.0,5.0,1.0,NaN,NaN,NaN
14,4656,4.0,4.0,NaN,NaN,5.0,5.0,2.0,NaN,3.0,...,NaN,1.0,3.0,NaN,2.0,NaN,3.0,NaN,3.0,1.0
15,4796,NaN,NaN,1.0,NaN,3.0,2.0,NaN,2.0,NaN,...,5.0,NaN,NaN,NaN,5.0,2.0,2.0,4.0,3.0,4.0
16,6037,NaN,NaN,NaN,NaN,4.0,NaN,2.0,NaN,2.0,...,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
17,3048,4.0,5.0,1.0,5.0,1.0,1.0,4.0,NaN,5.0,...,NaN,NaN,NaN,4.0,NaN,NaN,2.0,1.0,2.0,5.0
18,4790,5.0,1.0,NaN,NaN,NaN,4.0,2.0,1.0,3.0,...,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
19,4489,1.0,2.0,2.0,4.0,5.0,NaN,2.0,3.0,2.0,...,1.0,NaN,NaN,5.0,5.0,4.0,3.0,5.0,3.0,NaN

## Mean Rating: Calculate the mean rating for each movie, order with the highest rating listed first, and submit the top 5.

In [4]:
aiRatings.describe()

,User,260: Star Wars: Episode IV - A New Hope (1977),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),1: Toy Story (1995),2028: Saving Private Ryan (1998),296: Pulp Fiction (1994),...,2396: Shakespeare in Love (1998),2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995)
count,20.000000,15.000000,14.000000,10.000000,10.000000,16.00000,12.000000,17.000000,11.000000,11.000000,...,11.000000,12.000000,13.000000,9.000000,12.000000,12.000000,12.000000,12.000000,11.000000,10.000000
mean,3658.100000,3.266667,3.000000,2.700000,3.600000,3.06250,2.916667,2.823529,3.000000,3.000000,...,2.909091,1.916667,2.769231,3.222222,3.166667,2.833333,3.000000,2.833333,2.909091,3.000000
std,1749.716756,1.387015,1.467599,1.337494,1.646545,1.28938,1.564279,1.131111,1.414214,1.183216,...,1.513575,0.996205,1.235168,1.092906,1.585923,1.527525,1.595448,1.642245,1.578261,1.414214
min,139.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2558.750000,2.000000,2.000000,2.000000,2.500000,2.00000,1.750000,2.000000,2.000000,2.000000,...,2.000000,1.000000,2.000000,2.000000,2.000000,1.750000,2.000000,1.000000,1.500000,2.000000
50%,4252.500000,4.000000,3.000000,2.500000,4.000000,3.00000,3.000000,2.000000,3.000000,3.000000,...,3.000000,2.000000,3.000000,3.000000,3.000000,2.500000,2.500000,3.000000,3.000000,2.500000
75%,4916.250000,4.000000,4.000000,3.750000,5.000000,4.00000,4.000000,4.000000,4.000000,4.000000,...,4.000000,2.250000,4.000000,4.000000,5.000000,4.000000,5.000000,4.250000,4.000000,4.000000
max,6037.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,...,5.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

## % of ratings 4+: Calculate the percentage of ratings for each movie that are 4 or higher. Order with the highest percentage first, and submit the top 5.

In [130]:
top5List = pd.DataFrame()
for i in aiRatings.columns:
    if(i!='User'):
        value = aiRatings[i][aiRatings[i] >=4].count()
        totalCount = aiRatings[i].count()
        top5List.loc[:,i] = pd.Series((value/totalCount)*100)

In [132]:
top5List.transpose().sort([0],ascending=[0])

/Users/tuhung-te/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

                                                            0
318: Shawshank Redemption, The (1994)               70.000000
260: Star Wars: Episode IV - A New Hope (1977)      53.333333
3578: Gladiator (2000)                              50.000000
541: Blade Runner (1982)                            44.444444
593: Silence of the Lambs, The (1991)               43.750000
2571: Matrix, The (1999)                            41.666667
1265: Groundhog Day (1993)                          41.666667
34: Babe (1995)                                     40.000000
296: Pulp Fiction (1994)                            36.363636
1259: Stand by Me (1986)                            36.363636
2028: Saving Private Ryan (1998)                    36.363636
1210: Star Wars: Episode VI - Return of the Jed...  35.714286
1: Toy Story (1995)                                 35.294118
527: Schindler's List (1993)                        33.333333
2762: Sixth Sense, The (1999)                       33.333333
780: Independence Day (ID4) (1996)                  30.769231
356: Forrest Gump (1994)                            30.000000
1198: Raiders of the Lost Ark (1981)                27.272727
2396: Shakespeare in Love (1998)                    27.272727
2916: Total Recall (1990)                            8.333333

## Rating Count: Count the number of ratings for each movie, order with the most number of ratings first, and submit the top 5.

In [126]:
Rating_Count = aiRatings.copy()
del Rating_Count['User']
Rating_Count.describe().transpose().sort(['count'],ascending=[0])

/Users/tuhung-te/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

,count,mean,std,min,25%,50%,75%,max
1: Toy Story (1995),17.0,2.823529,1.131111,1.0,2.00,2.0,4.00,5.0
"593: Silence of the Lambs, The (1991)",16.0,3.062500,1.289380,1.0,2.00,3.0,4.00,5.0
260: Star Wars: Episode IV - A New Hope (1977),15.0,3.266667,1.387015,1.0,2.00,4.0,4.00,5.0
1210: Star Wars: Episode VI - Return of the Jedi (1983),14.0,3.000000,1.467599,1.0,2.00,3.0,4.00,5.0
780: Independence Day (ID4) (1996),13.0,2.769231,1.235168,1.0,2.00,3.0,4.00,5.0
"2762: Sixth Sense, The (1999)",12.0,2.833333,1.642245,1.0,1.00,3.0,4.25,5.0
3578: Gladiator (2000),12.0,2.916667,1.564279,1.0,1.75,3.0,4.00,5.0
527: Schindler's List (1993),12.0,3.000000,1.595448,1.0,2.00,2.5,5.00,5.0
"2571: Matrix, The (1999)",12.0,2.833333,1.527525,1.0,1.75,2.5,4.00,5.0
1265: Groundhog Day (1993),12.0,3.166667,1.585923,1.0,2.00,3.0,5.00,5.0
2916: Total Recall (1990),12.0,1.916667,0.996205,1.0,1.00,2.0,2.25,4.0
1198: Raiders of the Lost Ark (1981),11.0,2.909091,1.578261,1.0,1.50,3.0,4.00,5.0
2396: Shakespeare in Love (1998),11.0,2.909091,1.513575,1.0,2.00,3.0,4.00,5.0
1259: Stand by Me (1986),11.0,2.636364,1.501514,1.0,1.00,3.0,4.00,5.0
296: Pulp Fiction (1994),11.0,3.000000,1.183216,1.0,2.00,3.0,4.00,5.0
2028: Saving Private Ryan (1998),11.0,3.000000,1.414214,1.0,2.00,3.0,4.00,5.0
"318: Shawshank Redemption, The (1994)",10.0,3.600000,1.646545,1.0,2.50,4.0,5.00,5.0
356: Forrest Gump (1994),10.0,2.700000,1.337494,1.0,2.00,2.5,3.75,5.0
34: Babe (1995),10.0,3.000000,1.414214,1.0,2.00,2.5,4.00,5.0
541: Blade Runner (1982),9.0,3.222222,1.092906,2.0,2.00,3.0,4.00,5.0

In [139]:
aiRatings.where(np.isnan(aiRatings['260: Star Wars: Episode IV - A New Hope (1977)']))

,User,260: Star Wars: Episode IV - A New Hope (1977),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),1: Toy Story (1995),2028: Saving Private Ryan (1998),296: Pulp Fiction (1994),...,2396: Shakespeare in Love (1998),2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1577.0,NaN,NaN,NaN,5.0,2.0,NaN,4.0,NaN,NaN,...,NaN,1.0,4.0,4.0,1.0,1.0,2.0,3.0,1.0,3.0
3,4388.0,NaN,3.0,NaN,NaN,NaN,1.0,2.0,3.0,4.0,...,NaN,4.0,1.0,3.0,5.0,NaN,5.0,1.0,1.0,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5448.0,NaN,NaN,3.0,1.0,1.0,4.0,NaN,5.0,2.0,...,1.0,NaN,NaN,3.0,NaN,1.0,NaN,NaN,5.0,2.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4796.0,NaN,NaN,1.0,NaN,3.0,2.0,NaN,2.0,NaN,...,5.0,NaN,NaN,NaN,5.0,2.0,2.0,4.0,3.0,4.0
16,6037.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,NaN,2.0,...,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##  Top 5 Star Wars: Calculate movies that most often occur with Star Wars: Episode IV - A New Hope (1977) using the (x+y)/x method described in class. In other words, for each movie, calculate the percentage of Star Wars raters who also rated that movie. Order with the highest percentage first, and submit the top 5.

In [140]:
np.isnan(aiRatings['260: Star Wars: Episode IV - A New Hope (1977)'])

0     False
1     False
2      True
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
Name: 260: Star Wars: Episode IV - A New Hope (1977), dtype: bool

In [141]:
aiRatings

,User,260: Star Wars: Episode IV - A New Hope (1977),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),1: Toy Story (1995),2028: Saving Private Ryan (1998),296: Pulp Fiction (1994),...,2396: Shakespeare in Love (1998),2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995)
0,755,1.0,5.0,2.0,NaN,4.0,4.0,2.0,2.0,NaN,...,2.0,NaN,5.0,2.0,NaN,4.0,2.0,5.0,NaN,NaN
1,5277,5.0,3.0,NaN,2.0,4.0,2.0,1.0,NaN,NaN,...,3.0,2.0,2.0,NaN,2.0,NaN,5.0,1.0,3.0,NaN
2,1577,NaN,NaN,NaN,5.0,2.0,NaN,4.0,NaN,NaN,...,NaN,1.0,4.0,4.0,1.0,1.0,2.0,3.0,1.0,3.0
3,4388,NaN,3.0,NaN,NaN,NaN,1.0,2.0,3.0,4.0,...,NaN,4.0,1.0,3.0,5.0,NaN,5.0,1.0,1.0,2.0
4,1202,4.0,3.0,4.0,1.0,4.0,1.0,NaN,4.0,NaN,...,5.0,1.0,NaN,4.0,NaN,3.0,5.0,5.0,NaN,NaN
5,3823,2.0,4.0,4.0,4.0,NaN,NaN,3.0,1.0,4.0,...,5.0,2.0,4.0,NaN,1.0,NaN,NaN,3.0,NaN,2.0
6,5448,NaN,NaN,3.0,1.0,1.0,4.0,NaN,5.0,2.0,...,1.0,NaN,NaN,3.0,NaN,1.0,NaN,NaN,5.0,2.0
7,5347,4.0,NaN,NaN,NaN,3.0,2.0,2.0,NaN,3.0,...,NaN,2.0,3.0,2.0,4.0,NaN,1.0,3.0,5.0,NaN
8,4117,5.0,1.0,NaN,4.0,2.0,4.0,4.0,4.0,NaN,...,2.0,3.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,5.0
9,2765,4.0,2.0,NaN,5.0,3.0,NaN,4.0,3.0,4.0,...,NaN,NaN,2.0,NaN,NaN,2.0,5.0,1.0,NaN,NaN
10,5450,2.0,1.0,5.0,NaN,NaN,5.0,5.0,NaN,NaN,...,NaN,3.0,2.0,NaN,NaN,1.0,NaN,2.0,1.0,4.0
11,139,3.0,5.0,2.0,NaN,2.0,NaN,2.0,NaN,1.0,...,3.0,NaN,3.0,NaN,2.0,5.0,NaN,NaN,NaN,2.0
12,1940,2.0,3.0,NaN,5.0,4.0,NaN,4.0,5.0,NaN,...,NaN,2.0,4.0,NaN,3.0,NaN,NaN,NaN,5.0,NaN
13,3118,3.0,NaN,3.0,NaN,2.0,NaN,3.0,NaN,NaN,...,NaN,1.0,2.0,2.0,3.0,5.0,1.0,NaN,NaN,NaN
14,4656,4.0,4.0,NaN,NaN,5.0,5.0,2.0,NaN,3.0,...,NaN,1.0,3.0,NaN,2.0,NaN,3.0,NaN,3.0,1.0
15,4796,NaN,NaN,1.0,NaN,3.0,2.0,NaN,2.0,NaN,...,5.0,NaN,NaN,NaN,5.0,2.0,2.0,4.0,3.0,4.0
16,6037,NaN,NaN,NaN,NaN,4.0,NaN,2.0,NaN,2.0,...,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
17,3048,4.0,5.0,1.0,5.0,1.0,1.0,4.0,NaN,5.0,...,NaN,NaN,NaN,4.0,NaN,NaN,2.0,1.0,2.0,5.0
18,4790,5.0,1.0,NaN,NaN,NaN,4.0,2.0,1.0,3.0,...,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
19,4489,1.0,2.0,2.0,4.0,5.0,NaN,2.0,3.0,2.0,...,1.0,NaN,NaN,5.0,5.0,4.0,3.0,5.0,3.0,NaN